version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.47
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  restaurantpos:
    container_name: restaurantpos
    image: restaurant-app:1.0.0
    environment:
      - RESTATE_RUNTIME_ENDPOINT=http://runtime:8080
    ports:
      - "5050:5050"  # exposed so that can be called when delivery services run outside docker compose
    entrypoint: ["java", "-cp", "@/app/jib-classpath-file", "dev.restate.sdk.examples.RestaurantMain"]

  driver_app:
    container_name: driver_app
    image: delivery-service:1.0.0
    entrypoint: ["java", "-cp", "@/app/jib-classpath-file", "dev.restate.sdk.examples.external.DriverMobileAppSimulator"]

# To run the delivery services directly (in IDE, standalone), comment out this service
  delivery_service:
    container_name: delivery_service
    image: delivery-service:1.0.0
    environment:
      - RESTAURANT_ENDPOINT=http://restaurantpos:5050

  runtime:
    image: docker.io/restatedev/restate:1.1.3
    depends_on:
      - jaeger
    ports:
      - "9070:9070"
      - "9071:9071"
      - "8080:8080"
    volumes:
      - ./restate-docker.toml:/restate.toml:Z,ro
    environment:
      - RESTATE_CONFIG=/restate.toml
# remove those comments when running delivery services directly (in IDE, standalone), so the runtime can reach out to them
#    extra_hosts:
#      - "delivery_service:host-gateway"

  runtimesetup:
    build:
      context: ./tools
    depends_on:
      - runtime
      - driver_app
      - restaurantpos
    restart: "no"
    entrypoint: ["sh", "-c", "-x", "sleep 5 &&
    echo '-w \"\\n\"' >> ~/.curlrc &&
    curl -i -s --fail -X POST 'runtime:9070/deployments' -H 'content-type: application/json' -d '{\"uri\": \"http://delivery_service:9080\"}' &&
    curl -i -s --fail -X POST 'runtime:9070/deployments' -H 'content-type: application/json' -d '{\"uri\": \"http://driver_app:9081\"}' &&
    sleep 3 && 
    curl -i -s --fail -X POST 'runtime:8080/DriverMobileAppSimulator/driver-A/startDriver' &&
    curl -i -s --fail -X POST 'runtime:8080/DriverMobileAppSimulator/driver-B/startDriver' &&
    exit 1"]

  foodorderingwebui:
    build:
      context: ./webui
    depends_on:
      - runtimesetup
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_ENABLE_KAFKA=false
